# Generated by Django 3.0.7 on 2021-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude of the squirrel')),
                ('Latitude', models.FloatField(help_text='Latitude of the squirrel')),
                ('Unique_Squirrel_Id', models.CharField(help_text='The unique ID of the squirrel', max_length=25)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the squirrel appears in the morning or afternoon?', max_length=16)),
                ('Date', models.DateField(blank=True, help_text='Date of appearance', null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, ''), ('?', '?')], help_text='Age of the squirrel', max_length=16)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '')], help_text='Fur color of the squirrel', max_length=16)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location', max_length=200)),
                ('Specific_Location', models.TextField(blank=True, help_text='Additional info of the location')),
                ('Running', models.NullBooleanField(help_text='Running')),
                ('Chasing', models.NullBooleanField(help_text='Chasing')),
                ('Climbing', models.NullBooleanField(help_text='Climbing')),
                ('Eating', models.NullBooleanField(help_text='Eating')),
                ('Foraging', models.NullBooleanField(help_text='Foraging')),
                ('Other_Activities', models.TextField(blank=True, help_text='Other Activities', null=True)),
                ('Kuks', models.NullBooleanField(help_text='Kuks')),
                ('Quaas', models.NullBooleanField(help_text='Quaas')),
                ('Moans', models.NullBooleanField(help_text='Moans')),
                ('Tail_Flags', models.NullBooleanField(help_text='Tail_Flags')),
                ('Tail_Twitches', models.NullBooleanField(help_text='Tail_Twitches')),
                ('Approaches', models.NullBooleanField(help_text='Approaches')),
                ('Indifferent', models.NullBooleanField(help_text='Indifferent')),
                ('Runs_From', models.NullBooleanField(help_text='Runs_From')),
            ],
        ),
    ]
